---
- name: Listen for events from AlertManager
  hosts: all

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Let Ansible print information about the alert
      condition: event.alert.status == "firing" or event.alert.status == "resolved"
      action:
        run_playbook:
          name: eda-playbook-alertmanager.yml

    - name: Debug Hello event
      condition: event.alert is defined
      action:
        debug:

